version: 1.0
provider:
  name: openfaas
  gateway: <openfaas-platform-url>
functions:
  application-service-image:
    lang: python3-debian
    handler: ./application-service-image
    image: <dockerhub-user>/application-service-image:latest
    environment:
      PRIMEHUB_DEPLOYMENT_URL: <primehub-deployment-url>